- name: Configure CDN Load Balancer
  hosts: webservers
  collections:
    - yoctoalex.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: fetch current tenant details
      fetch_tenant_settings:
      register: tenant

    - name: create cdn load balancer
      cdn_loadbalancer:
        state: present
        metadata:
          namespace: "default"
          name: "demo-cdn-lb"
        spec:
          domains:
            - "cdn.example.com"
          http:
            dns_volterra_managed: False
          add_location: False
          origin_pool:
            public_name:
              dns_name: "example.com"
            follow_origin_redirect: False
            no_tls: { }
            origin_servers:
              - public_name:
                  dns_name: "example.com"

    - name: delete cdn distribution
      cdn_loadbalancer:
        state: absent
        metadata:
          namespace: "default"
          name: "demo-cdn-lb"
        spec: