- name: Configure xC Cloud namespaces
  hosts: webservers
  collections:
    - yoctoalex.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: create namespace
      namespace:
        state: present
        wait: True
        metadata:
          name: "demonamespace"

    - name: fetch namespace
      namespace:
        state: fetch
        metadata:
          name: "demonamespace"

    - name: remove namespace
      namespace:
        state: absent
        metadata:
          name: "demonamespace"