- name: Configure Service Policy
  hosts: webservers
  collections:
    - yoctoalex.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: create service policy
      service_policy:
        state: present
        metadata:
          namespace: "default"
          name: "demo-policy"
        spec:
          algo: "FIRST_MATCH"
          any_server: {}
          rule_list:
            rules:
              - metadata:
                  name: "deny-all-except-api"
                spec:
                  action: "DENY"
                  path:
                    prefix_values:
                      - "/api/v1/"
                  api_group_matcher:
                    match:
                      - "ves-io-api-def-api-def-all-operations"
                    invert_matcher: True
                  challenge_action: "DEFAULT_CHALLENGE"
                  waf_action:
                    none: {}
              - metadata:
                  name: "allow-other"
                spec:
                  action: "ALLOW"
                  challenge_action: "DEFAULT_CHALLENGE"
                  waf_action:
                    none: { }

    - name: delete service policy
      service_policy:
        state: absent
        metadata:
          namespace: "default"
          name: "demo-policy"
        spec: